---
title: "Single Effect Regression Benchmarks"
format:
  html: 
    code-fold: true
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = '~/Research/logistic-susie-benchmarks/')
```

# Sum of Single Effect Regressions Benchmark

## Introduction

We take various SERs, and various strategies/objectives for combining them.

```{r}
library(targets)
library(tidyverse)

cs_scores <- tar_read(ibss_cs_coverage, store = '_targets/')
fit_methods <- unique(cs_scores$fit_method)

plot_colors <- c(
  'ibss_glm_L5' = 'aquamarine1', 
  'ibss_glm2_L5' = 'aquamarine3', 
  'ibss_uvb_L5' = 'brown1', 
  'ibss_uvb2_L5' = 'brown3', 
  'ibss_vb_L5' = 'darkgoldenrod1', 
  'ibss_vb2_L5' = 'darkgoldenrod3',
  'ibss_vbc_L5' = 'darkorange1',
  'binsusie_L5' = 'olivedrab3',
  'binsusie2_L5' = 'olivedrab4',
  'ibss2m_L5' = 'dodgerblue4'
  # 'veb_ser' = 'darkorchid1',
  # 'quad_ser' = 'deeppink1'
)
plot_colors <- plot_colors[names(plot_colors) %in% fit_methods]
method_order = names(plot_colors)

# coverage for each L
plot_data <- cs_scores %>%
  ungroup() %>%
  group_by(fit_method, L) %>%
  # distribution of mean(covered) over 20 bootstrap iterations
  mutate(coverage = list(purrr::map_dbl(1:20, ~mean(sample(covered, replace = T))))) %>%
  select(fit_method, coverage, L) %>%
  unnest_longer(coverage)
```

```{r}
plot <- plot_data %>%
  ggplot(aes(x=factor(fit_method, level = names(plot_colors)), y=coverage, fill=fit_method)) +
  geom_boxplot(outlier.shape=NA) + facet_wrap(vars(L)) +
  scale_fill_manual(values=plot_colors) +
  theme(axis.text.x = element_blank())
plot
```



```{r}
# coverage conditional on CS size
plot_data <- cs_scores %>%
  ungroup() %>%
  hoist(cs, size='size') %>%
  mutate(size_bin = cut(size, c(0, 1, 5, 10, 50))) %>%
  group_by(fit_method, size_bin, L) %>%
  mutate(coverage = list(purrr::map_dbl(1:50, ~mean(sample(covered, replace = T))))) %>%
  select(fit_method, size_bin, coverage, L) %>%
  unnest_longer(coverage)

plot <- plot_data %>% 
  ggplot(aes(x=size_bin, y=coverage, fill=factor(fit_method, level=method_order))) +
  geom_boxplot(outlier.shape=NA) + facet_grid(rows=vars(L)) +
  scale_fill_manual(values=plot_colors)
plot
```


```{r}
roc_plot_data <- tar_read(ibss_pip_roc, store='_targets/')

roc_plot_data %>%
  ggplot(aes(d=causal, m = pip, color=fit_method)) +
  plotROC::geom_roc(n.cuts = 0, size.point=1, size=0.5) + 
  scale_color_manual(values=plot_colors) +
  xlim(0, 0.2) + 
  ylim(0, 0.6)
```


```{r}
pip_bins <- seq(0, 1.0, by=0.05)

get_y_range <- function(y){
  res <- quantile(purrr::map_dbl(1:50, ~mean(sample(y, replace = T))), c(0.05, 0.5, 0.95))
  names(res) <- c('ymin', 'y', 'ymax')
  return(as.list(res))
}

pip_calibration_data <- roc_plot_data %>%
  mutate(pip_bin = cut(pip, pip_bins, labels=F)) %>%
  mutate(pip_bin = seq(0.05, 1.0, by=0.05)[pip_bin]) %>%
  group_by(fit_method, pip_bin) %>%
  summarise(
    y_range = list(get_y_range(causal))
  ) %>%
  ungroup()

pip_calibration_data %>%
  unnest_wider(y_range) %>%
  ggplot(aes(x=pip_bin, y=y, ymin=ymin, ymax=ymax)) + 
  geom_pointrange(size=0.1) +
  geom_abline(intercept = 0, slope = 1, color='red') +
  facet_wrap(vars(fit_method), ncol = 4) +
  theme_bw()
```

```{r}
# coverage of SERs for different true L
cs_scores %>%
  ungroup() %>%
  hoist(cs, size='size') %>%
  group_by(fit_method, L) %>%
  mutate(coverage = list(purrr::map_dbl(1:100, ~mean(sample(covered, replace = T))))) %>%
  select(fit_method, L, coverage) %>%
  unnest_longer(coverage) %>%
  ggplot(aes(x=factor(L), y=coverage, fill=factor(fit_method, levels = method_order))) +
  scale_fill_manual(values=plot_colors) + 
  geom_boxplot(outlier.shape=NA)
```
